name: Publish
on:
  release:
    types: [published]

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Version
        uses: pocket-apps/action-update-version@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Version Change
        run: git pull origin master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: "@pocket-apps"
      - name: Install Dependencies
        run: yarn install
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-github:
    name: Publish Github
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Version Change
        run: git pull origin master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@pocket-apps"
      - name: Install Dependencies
        run: yarn install
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
